### ISSUE TITLE
CCleaner remove context menu

### ISSUE THREAD

**Issue by circcc** [jpc-ae/Snippets#1]
When I clean Edge with CCleaner, the Paste Snippets item in the context menu disappears. I investigated and found that CCleaner > Cusom Clean > Windows Tab > Edge Chromium > Session is deleting files in the C:\Users\xxxxx\AppData\Local\Microsoft\Edge\User Data\Default\Extension State folder. 
Please fix the bug so that the context menu remains even if files in this folder are deleted.

**Comment by jpc-ae** [comment]
Context menus are currently updated through the browser API when the extension is installed or updated, and when snippets are changed in any way (add/edit/delete). The extension itself has no knowledge of where or how the browser adds and stores them. If deleting files in that folder clears the context menu, it will need to be rebuilt (filling that folder again).

I would recommend exluding that folder from CCleaner when you run it, but I will try to find a listener I can use to rebuild the menu in a timely manner. At the very least, I will add a check to the next version for the context menu when the browser opens and rebuild it then when necessary.

**Comment by jpc-ae** [comment]
Since the files can only be deleted with Edge closed I've set the contextmenus to be rebuilt on open of the browser. I would still recommend ignoring this folder in CCleaner however.

See https://github.com/jpc-ae/Snippets/commit/74bc9fdc0df12f3596542228b73404294c43ced7

This will be included in the next update.
